sudo: required
dist: trusty
services: postgresql
addons:
    postgresql:
        9.4

language: python
python:
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq lighttpd
    - pip install django psycopg2 gitpython
    - sudo -E ./.travis/setup-paths.sh

script:
    - ./.travis/run-test.sh
    - ./.travis/deploy.sh

notifications:
    email:
        - kangirigungi@gmail.com
    on_success: change
    on_failure: always

