sudo: required
dist: trusty
services: postgresql

language: python
python:
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq lighttpd
    - pip install django psycopg2 gitpython
    - sudo apt-get install -qq tree
    - tree /usr/local/lib
    - find / -name django 2>/dev/null || true
    - which python
    - which python3
    - which pip
    - echo $PYTHONPATH
    - echo $PATH

script:
    - python3 ./server/home_automation/manage.py test
    - ./deploy/create_deployment.py --type=install --system=upstart
    - mkdir -p custom/install
    - cd custom/install
    - tar -xf ../../home_automation.tar.gz
    - sudo bash -x ./home_automation/install.sh

notifications:
    email:
        - kangirigungi@gmail.com
    on_success: change
    on_failure: always

