sudo: required
dist: trusty
services: postgresql

language: python
python:
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install lighttpd
    - pip install django psycopg2 gitpython

script:
    - ./deploy/create_deployment.py --type=install
    - mkdir -p custom/install
    - cd custom/install
    - tar -xf ../../home_automation.tar.gz
    - sudo ./home_automation/install.sh

notifications:
    email:
        - kangirigungi@gmail.com
    on_success: change
    on_failure: always

